---
- hosts: localhost
  connection: local

  tasks:

    - name: create folders
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.config"
        - "~/.zsh_logs"
     
    - name: install and configure oh-my-zsh
      block:

        - name: install oh-my-zsh
          shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        - name: install oh-my-zsh theme
          copy:
            src: ./omz-theme.template
            dest: ~/.oh-my-zsh/themes/mine.zsh-theme
            owner: "{{ ansible_user_id }}"
            group: staff
            mode: '0644'

        - name: install zshrc
          copy:
            src: ./zshrc.template
            dest: ~/.zshrc
            owner: "{{ ansible_user_id }}"
            group: staff
            mode: '0644'

    - name: check if homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: brew_exists

    - name: install homebrew
      shell: echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew_exists.stat.exists
      
    - name: update homebrew and homebrew installed apps
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: install base tools (homebrew)
      homebrew:
        name:
          - borg
          - espanso
          - ffmpeg
          - git
          - imagemagick
          - maccy
          - mas
          - nmap
          - python@3.9
          - rsync
          - the_silver_searcher          
          - tmate
          - tmux
          - watch
          - wget
          - youtube-dl
        state: present

    - name: install apps (homebrew)
      homebrew_cask:
        name:
          - 1password
          - alfred
          - arq
          - backblaze
          - bartender
          - beyond-compare
          - firefox
          - font-source-code-pro
          - google-chrome
          - iina
          - iterm
          - itsycal
          - java
          - microsoft-edge
          - moonlight
          - rectangle
          - steam
          - visual-studio-code
        state: present
        
    - name: install mac store apps
      command: "mas install {{ item }}"
      loop:
        - 890031187   # Marked 2
        - 290986013   # Deliveries
        - 1480933944  # Vimari
        - 1474276998  # HP Smart
        - 1451685025  # WireGuard
        - 1448441317  # Scrap Paper
        - 1295203466  # Microsoft Remote Desktop
        - 1289583905  # Pixelmator Pro
        - 1284863847  # Unsplash Wallpapers
        - 1055511498  # Day One
        - 1055273043  # PDF Expert

